version: 2
updates:
  # Maintain App gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/dependencies.gradle"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    labels:
      - "Dependencies"
